//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong_WebsiteTimPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseBill
    {
        public int IdHouseBill { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public string TienPhong { get; set; }
        public Nullable<decimal> SoDienCu { get; set; }
        public Nullable<decimal> SoNuocCu { get; set; }
        public Nullable<decimal> SoDienMoi { get; set; }
        public Nullable<decimal> SoNuocMoi { get; set; }
        public Nullable<decimal> TienDien { get; set; }
        public Nullable<decimal> TienNuoc { get; set; }
        public Nullable<decimal> TienRac { get; set; }
        public Nullable<decimal> TienWifi { get; set; }
        public Nullable<decimal> KhoanThuKhac { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
